apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  annotations: 
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: transaction
    tsb.tetrate.io/workspace: blogger-ws
  name: blogger-security
spec:
  displayName: blogger-security-group
  namespaceSelector:
    names:
      - "cp-cluster-1/transaction"
  configMode: BRIDGED
  