apiVersion: v1
kind: Service
metadata:
  name: blogger
  namespace: content
  labels:
    app: blogger
    service: blogger
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app.kubernetes.io/name: blogger-api